spring.application.name=demo
# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# This shows the actual SQL Postgres is trying to run
spring.jpa.properties.hibernate.format_sql=true
# This gives you the detailed error from the Postgres driver
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# H2 Database Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Radiant@2019

# jwt key
jwt.secret=your_very_long_and_very_secure_secret_key_here_at_least_32_chars


management.endpoint.metrics.enabled=true
management.metrics.export.simple.enabled=true
spring.cache.type=simple


# Expose actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Show detailed health info
management.endpoint.health.show-details=always

# Metrics tagging (important for dashboards)
management.metrics.tags.application=feed-aggregation-service

